name: Continuous Integration

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.20']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Run lint with go version ${{ matrix.go }}
        run: make lint

      - name: Run tests with go version ${{ matrix.go }}
        run: make integration
    
